net: ethernet: fec_main: Fixed compilation error
As per commit 4f49dec9075a ("net: allow ndo_select_queue to pass netdev")
make changes in the patch to fix the below compilation error.

drivers/net/ethernet/freescale/fec_main.c:3358:28: error: initialization of ‘u16 (*)(struct net_device *, struct sk_buff *, struct net_device *, u16 (*)(struct net_device *, struct sk_buff *, struct net_device *))’ {aka ‘short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *, short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *))’} from incompatible pointer type ‘u16 (*)(struct net_device *, struct sk_buff *, void *, u16 (*)(struct net_device *, struct sk_buff *, struct net_device *))’ {aka ‘short unsigned int (*)(struct net_device *, struct sk_buff *, void *, short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *))’} [-Werror=incompatible-pointer-types]
  .ndo_select_queue       = fec_enet_select_queue,
                            ^~~~~~~~~~~~~~~~~~~~~
drivers/net/ethernet/freescale/fec_main.c:3358:28: note: (near initialization for ‘fec_netdev_ops.ndo_select_queue’)
  AR      drivers/watchdog/built-in.a
cc1: some warnings being treated as errors
scripts/Makefile.build:303: recipe for target 'drivers/net/ethernet/freescale/fec_main.o' failed

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>