ASoC: cs42xx8: fixed compilation errors
As per commit 99a9f452093e ("ASoC: cs42xx8: replace codec to component")
replaced codec to component to fix the below compilation errors.

sound/soc/codecs/cs42xx8.c: In function ‘cs42xx8_hw_params’:
sound/soc/codecs/cs42xx8.c:282:12: error: ‘codec’ undeclared (first use in this function); did you mean ‘cdev’?
    dev_err(codec->dev, "unsupported sample rate or rate combine\n");
            ^~~~~
./include/linux/device.h:1418:11: note: in definition of macro ‘dev_err’
  _dev_err(dev, dev_fmt(fmt), ##__VA_ARGS__)
           ^~~
sound/soc/codecs/cs42xx8.c:282:12: note: each undeclared identifier is reported only once for each function it appears in
    dev_err(codec->dev, "unsupported sample rate or rate combine\n");
            ^~~~~
./include/linux/device.h:1418:11: note: in definition of macro ‘dev_err’
  _dev_err(dev, dev_fmt(fmt), ##__VA_ARGS__)
           ^~~
sound/soc/codecs/cs42xx8.c: In function ‘cs42xx8_hw_free’:
sound/soc/codecs/cs42xx8.c:343:35: error: ‘struct snd_soc_pcm_runtime’ has no member named ‘codec’
  struct snd_soc_codec *codec = rtd->codec;
                                   ^~
sound/soc/codecs/cs42xx8.c:344:33: error: implicit declaration of function ‘snd_soc_codec_get_drvdata’; did you mean ‘snd_soc_dai_get_drvdata’? [-Werror=implicit-function-declaration]
  struct cs42xx8_priv *cs42xx8 = snd_soc_codec_get_drvdata(codec);
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
                                 snd_soc_dai_get_drvdata
sound/soc/codecs/cs42xx8.c:344:33: warning: initialization of ‘struct cs42xx8_priv *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
cc1: some warnings being treated as errors
scripts/Makefile.build:305: recipe for target 'sound/soc/codecs/cs42xx8.o' failed
make[3]: *** [sound/soc/codecs/cs42xx8.o] Error 1

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Srikanth Krishnakar <Srikanth_Krishnakar@mentor.com>