brcmfmac: Rename / replace old IO functions with simpler ones.
As per 'commit 71bd508d7ded ("brcmfmac: Rename / replace old IO functions
with simpler ones.")', rename/ replace old IO functions to fix the
compilation errors.

drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.c: In function ‘brcmf_sdio_firmware_callback’:
drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.c:4116:4: error: implicit declaration of function ‘brcmf_sdiod_regwb’; did you mean ‘brcmf_sdiod_readb’? [-Werror=implicit-function-declaration]
    brcmf_sdiod_regwb(sdiodev, SBSDIO_WATERMARK, CY_4373_F2_WATERMARK, &err);
    ^~~~~~~~~~~~~~~~~
    brcmf_sdiod_readb
drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.c:4116:22: error: ‘sdiodev’ undeclared (first use in this function); did you mean ‘sdiod’?
    brcmf_sdiod_regwb(sdiodev, SBSDIO_WATERMARK, CY_4373_F2_WATERMARK, &err);
                      ^~~~~~~
                      sdiod
drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.c:4116:22: note: each undeclared identifier is reported only once for each function it appears in
drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.c:4117:13: error: implicit declaration of function ‘brcmf_sdiod_regrb’; did you mean ‘brcmf_sdiod_readb’? [-Werror=implicit-function-declaration]
    devctl = brcmf_sdiod_regrb(sdiodev, SBSDIO_DEVICE_CTL, &err);
             ^~~~~~~~~~~~~~~~~
             brcmf_sdiod_readb
cc1: some warnings being treated as errors
scripts/Makefile.build:303: recipe for target 'drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.o' failed

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>