mmc: block: Fix compilation error
As per 'commit 8814ce8a0f68 ("block: Introduce blk_queue_flag_{set,clear,test_and_{set,clear}}()")'
, make changes to fix the below compilation error.

drivers/mmc/core/block.c: In function ‘mmc_blk_remove_req’:
drivers/mmc/core/block.c:2672:3: error: implicit declaration of function ‘queue_flag_set’; did you mean ‘blk_queue_flag_set’? [-Werror=implicit-function-declaration]
   queue_flag_set(QUEUE_FLAG_BYPASS, md->queue.queue);
   ^~~~~~~~~~~~~~
   blk_queue_flag_set
cc1: some warnings being treated as errors
scripts/Makefile.build:303: recipe for target 'drivers/mmc/core/block.o' failed

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>