ASoC: fsl_esai: fixed compilation error
As per commit ef050bece1b5 ("ASoC: Remove platform code now everything is
componentised"), replace platform to component to fix the compilation
errors.

sound/soc/fsl/fsl_esai.c: In function ‘fsl_esai_probe’:
sound/soc/fsl/fsl_esai.c:1056:8: error: implicit declaration of function ‘imx_pcm_platform_register’; did you mean ‘imx_rpmsg_platform_register’? [-Werror=implicit-function-declaration]
  ret = imx_pcm_platform_register(&pdev->dev);
        ^~~~~~~~~~~~~~~~~~~~~~~~~
        imx_rpmsg_platform_register
cc1: some warnings being treated as errors
scripts/Makefile.build:305: recipe for target 'sound/soc/fsl/fsl_esai.o' failed
make[3]: *** [sound/soc/fsl/fsl_esai.o] Error 1
scripts/Makefile.build:546: recipe for target 'sound/soc/fsl' failed
make[2]: *** [sound/soc/fsl] Error 2
scripts/Makefile.build:546: recipe for target 'sound/soc' failed
make[1]: *** [sound/soc] Error 2
Makefile:1052: recipe for target 'sound' failed
make: *** [sound] Error 2

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Srikanth Krishnakar <Srikanth_Krishnakar@mentor.com>