MLK-21076-1 rtc: imx-rpmsg: Fix build error when CONFIG_PM_SLEEP=n
drivers/rtc/rtc-imx-rpmsg.c:374:9:
error: 'IMX_RPMSG_RTC_PM_OPS' undeclared here (not in a function);
did you mean 'IMX8_RPMSG_RTC_PM_OPS'?

   .pm = IMX_RPMSG_RTC_PM_OPS,
         ^~~~~~~~~~~~~~~~~~~~
         IMX8_RPMSG_RTC_PM_OPS

Signed-off-by: Anson Huang <Anson.Huang@nxp.com>
Reviewed-by: Jacky Bai <ping.bai@nxp.com>
(cherry picked from commit 86aba1097ae69ff75999bddc3c3b0ad6c0bc7e2e)