media: v4l2-core: Fix compilation error
As per commit 73a110623e7b ("media: v4l2-core: push taking ioctl mutex down
to ioctl handler"), make changes to fix the below compilation error.

drivers/media/v4l2-core/v4l2-dev.c: In function ‘v4l2_ioctl’:
drivers/media/v4l2-core/v4l2-dev.c:363:24: error: implicit declaration of function ‘v4l2_ioctl_get_lock’; did you mean ‘v4l2_ioctl’? [-Werror=implicit-function-declaration]
   struct mutex *lock = v4l2_ioctl_get_lock(vdev, cmd);
                        ^~~~~~~~~~~~~~~~~~~
                        v4l2_ioctl
drivers/media/v4l2-core/v4l2-dev.c:363:24: warning: initialization of ‘struct mutex *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  CC      drivers/media/v4l2-core/v4l2-clk.o

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>